# Generated by Django 5.2.1 on 2026-06-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='created', help_text='Current order status', max_length=20)),
                ('amount', models.BigIntegerField(help_text='Amount in minor units (cents/tiyn) to avoid float precision issues')),
                ('currency', models.CharField(default='KZT', help_text='ISO 4217 currency code', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Order description')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate charges', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor', models.CharField(help_text='Who triggered the transition (user, system, webhook, etc.)', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='payments.order')),
            ],
            options={
                'verbose_name': 'State Transition Log',
                'verbose_name_plural': 'State Transition Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Provider transaction ID', max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('bereke', 'Bereke Bank'), ('paypal', 'PayPal')], help_text='Payment provider', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('amount', models.BigIntegerField(help_text='Amount in minor units (cents/tiyn)')),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevent duplicate submissions', max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data')),
                ('refund_amount', models.BigIntegerField(default=0, help_text='Amount refunded in minor units')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='payments_or_user_id_0f08a8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='payments_or_user_id_f610cb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='payments_or_status_daab12_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['idempotency_key'], name='payments_or_idempot_c5a9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='statetransitionlog',
            index=models.Index(fields=['order', 'timestamp'], name='payments_st_order_i_ba96d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', 'status'], name='payments_tr_order_i_028313_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider', 'status'], name='payments_tr_provide_cb836c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='payments_tr_transac_e96a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='payments_tr_idempot_801f50_idx'),
        ),
    ]
