# Generated by Django 6.0.1 on 2026-01-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зарплата')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
