# Generated by Django 6.0.1 on 2026-01-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_job_options_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(default='admin@example.com', max_length=254, verbose_name='Email для отклика'),
        ),
    ]
