# Generated by Django 6.0.2 on 2026-03-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_job_employer_profile_role_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.job'),
        ),
    ]
