# Generated by Django 6.0.2 on 2026-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_application_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент / Соискатель'), ('employer', 'Работодатель'), ('admin', 'Администратор')], default='student', max_length=10),
        ),
    ]
