# Generated by Django 6.0.3 on 2026-06-01 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_phone_alter_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='accounts_fa_user_id_6c6f24_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['job'], name='accounts_fa_job_id_8d26f8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='accounts_jo_company_a86aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone'], name='accounts_pr_phone_a8479a_idx'),
        ),
    ]
