# Generated by Django 5.2.1 on 2026-06-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_oauth_fields'),
        ('accounts', '0011_favorite_accounts_fa_user_id_6c6f24_idx_and_more'),
    ]

    operations = [
    ]
