# Generated by Django 5.2.1 on 2026-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260604_0929'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favorite',
            name='accounts_fa_user_id_6c6f24_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='accounts_fa_job_id_8d26f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='accounts_jo_company_a86aa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='accounts_pr_role_fae1f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='accounts_pr_phone_a8479a_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
