# Generated by Django 5.2.1 on 2026-08-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('internship', 'Стажировка'), ('contract', 'Контракт')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
